services:
  laravel-app_nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: myapp/nginx
    container_name: laravel-app_webserver
    ports:
      - "80:8000"
    volumes:
      - ./code:/code/
      - ./phpsocket:/run
    networks:
      - laravel-app_app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE}
      XDEBUG_CONFIG:
        client_host=host.docker.internal
        start_with_request=yes

  laravel-app_app:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: myapp/php
    container_name: laravel-app_app
    volumes:
      - ./code:/code/
      - ./phpsocket:/run
    networks:
      - laravel-app_app-network
    depends_on:
      - laravel-app_database
      - laravel-app_memcache
    environment:
      - PHP_IDE_CONFIG=serverName=IDE

  #  php-cli:
  #    build:
  #      context: ./php-cli
  #      dockerfile: Dockerfile
  #    image: myapp/php # можно использовать тот же образ, что и для PHP-FPM
  #    container_name: php-cli
  #    volumes:
  #      - ./code:/code/
  #    networks:
  #      - app-network
  #    tty: true

  laravel-app_memcache:
    image: memcached:latest
    container_name: laravel-app_memcached
#    ports:
#      - "11211:11211"
    command: memcached -m 64
    networks:
      - laravel-app_app-network

  laravel-app_database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: laravel-app_database
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - laravel-app_app-network

#Docker Networks
networks:
  laravel-app_app-network:
    driver: bridge